version: "2"
services:
  web:
    build: .
    ports:
      - "3001:3001"
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./data/mongodb/db:/data/db
    ports:
      - "27017:27017"
  test:
      build:
         context: .
         dockerfile: Dockerfile.test
      links:
        - mongo
        - web
